### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by David-Guillot** [erickok/transdroid-search#45]
Hello there,

I'm a long-time happy user of this app, I get it from F-Droid.

I noticed that some of its torrent sites don't exist anymore, maybe some new ones could be added. I also noticed there are some Pull Request pending since last November, so I have to ask: @erickok, are you still maintaining this app?

If you don't want to, or if you are not able to right now, it's totally understandable, but if you want the app to live without you (at least for a while), there are 2 things the community needs:
* A place to submit Pull Requests that have a chance to be merged ; this can be an existing fork (for example [this one](https://github.com/thismachinechills/transdroid-search) if @thismachinechills agrees ; I can also create one, I'll be available to merge PRs but I have no Android development skills...)
* A place to distribute new releases: I already created [this Merge Request](https://gitlab.com/fdroid/fdroiddata/merge_requests/1578) to push 3.5 on F-Droid, I could do the same for next releases, but http://transdroid.org/latest-search would have to be updated as well, and I don't know who could do that...

Anyway @erickok nobody else than you can decide what's next, and the only thing I can tell you it's a big thank you for this very useful app ;)

**Comment by erickok** [comment]
I will support it. I have not been motivated much or have had much time, but that's partly because not much was going on. I would love some external support and help but I never found really someone for that.

Yes I should absolutely go over the list of PRs and see if all the current providers still work. I used to do this more frequently, but as stated wasn't much motivated. I will try to make some time.

For distributions, the guys from tTorrent can actually also make releases, but notmally I would still do that. Releasing is the least amount of work and I am happy to do that.

**Comment by erickok** [comment]
All PRs merged and some adapters fixed/removed. New release imminent.
